"""PSB-MPC Taichi: GPU-accelerated collision avoidance for autonomous ships."""

from .types import (
    PSBMPCParameters,
    SBMPCParameters,
    ShipState4,
    ShipState6,
    ObstacleData,
    CPEResult,
    MPCResult,
    Waypoint,
)
from .ship_models import Kinematic_Ship, Obstacle_Ship, Kinetic_Ship
from .cpe import CPE
from .cost import Path_Grounding_Cost, Dynamic_Obstacle_Cost, MPC_Cost, COLREGS_Evaluator
from .mpc import PSBMPC_Solver, SBMPC_Solver
from .utils import (
    Xoshiro256pp,
    normalize_angle,
    angle_diff,
    distance_2d,
    bearing_2d,
    cross_2d,
    dot_2d,
    point_to_segment_distance,
    point_in_polygon,
    line_segment_intersection,
    ship_polygon,
    polygon_distance,
    utm_to_latlon,
    latlon_to_utm,
    generate_norm_samples,
    clamp,
    lerp,
    wrap_angle,
    squared_distance_2d,
)

__all__ = [
    "PSBMPCParameters",
    "SBMPCParameters",
    "ShipState4",
    "ShipState6",
    "ObstacleData",
    "CPEResult",
    "MPCResult",
    "Waypoint",
    "Kinematic_Ship",
    "Kinetic_Ship",
    "Obstacle_Ship",
    "CPE",
    "Path_Grounding_Cost",
    "Dynamic_Obstacle_Cost",
    "MPC_Cost",
    "COLREGS_Evaluator",
    "PSBMPC_Solver",
    "SBMPC_Solver",
    "Xoshiro256pp",
    "normalize_angle",
    "angle_diff",
    "distance_2d",
    "bearing_2d",
    "cross_2d",
    "dot_2d",
    "point_to_segment_distance",
    "point_in_polygon",
    "line_segment_intersection",
    "ship_polygon",
    "polygon_distance",
    "utm_to_latlon",
    "latlon_to_utm",
    "generate_norm_samples",
    "clamp",
    "lerp",
    "wrap_angle",
    "squared_distance_2d",
]
